/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentId = IDL.Text;
export const ClassId = IDL.Text;
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'studentId' : StudentId,
  'classId' : ClassId,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudentProfile = IDL.Record({
  'studentId' : StudentId,
  'name' : IDL.Text,
  'faceData' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(StudentId),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAttendanceByClass' : IDL.Func(
      [ClassId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFaceRecognitionData' : IDL.Func(
      [StudentId],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func(
      [StudentId],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func([StudentId, ClassId], [], []),
  'registerAdminUser' : IDL.Func([], [], []),
  'registerStudentProfile' : IDL.Func([StudentProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStudentProfile' : IDL.Func([StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentId = IDL.Text;
  const ClassId = IDL.Text;
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'studentId' : StudentId,
    'classId' : ClassId,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudentProfile = IDL.Record({
    'studentId' : StudentId,
    'name' : IDL.Text,
    'faceData' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(StudentId),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getAttendanceByClass' : IDL.Func(
        [ClassId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFaceRecognitionData' : IDL.Func(
        [StudentId],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [StudentId],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func([StudentId, ClassId], [], []),
    'registerAdminUser' : IDL.Func([], [], []),
    'registerStudentProfile' : IDL.Func([StudentProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStudentProfile' : IDL.Func([StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };